server:
  port: 8080

logging:
  path: /Users/zgl/Desktop
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      mybaties: ERROR

REDIS:
  URL: 192.168.20.112
  PORT: 6379

hbase:
  master: master:60000
  zookeeper:
    quorum: master,slave1,slave2
    property:
      clientPort: 2181
zookeeper:
  znode:
    parent: /hbase

kafka:
  consumer:
    zookeeper:
      connect: 127.0.0.1:2182
    servers: 127.0.0.1:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: mhd-notice
    group:
      id: mhd-notice
    concurrency: 10
  producer:
    servers: 127.0.0.1:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960
phoenix:
  enable: true
  url: jdbc:phoenix:192.168.20.128
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  username:
  password:
  default-auto-commit: true