server:
  port: 8088

logging:
  path: /Users/zgl/Desktop
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      mybaties: ERROR

REDIS:
  URL: 192.168.20.112
  PORT: 6379

hbase:
  master: master:60000
  zookeeper:
    quorum: hadoop-master,hadoop-slave01,hadoop-slave02
    property:
      clientPort: 2181
  split:
    info: 1,2,3,4,5,6,7,8,9,A,B,C,D,E,F  #表预切分
zookeeper:
  znode:
    parent: /hbase

kafka:
  consumer:
    zookeeper:
      connect: 192.168.10.83:2181,192.168.10.84:2181,192.168.10.85:2181,
    servers: 192.168.10.83:9092,192.168.10.84:9092,192.168.10.85:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: mhd-notice
    group:
      id: mhd-notice
    concurrency: 10
  producer:
    servers: 192.168.20.112:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960

phoenix:
  enable: true
  url: jdbc:phoenix:hadoop-master,hadoop-slave01,hadoop-slave02:2181
  type: com.alibaba.druid.pool.DruidDataSource
  validationQuery: select 1
  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  username:
  password:
  default-auto-commit: true
